services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=config/dev.json
    restart: unless-stopped
    depends_on:
      - postgres

  crawler:
    build: ./crawler
    environment:
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql


  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  pgdata:
  redis_data: