services:
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY}/backend:${IMAGE_TAG:-latest}
    ports:
      - "127.0.0.1:8083:8080"
    environment:
      - CONFIG_PATH=config/prod.json
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - REDIS_HOST=${REDIS_BACKEND_HOST}
      - REDIS_PORT=${REDIS_BACKEND_PORT}
      - REDIS_PASSWORD=${REDIS_BACKEND_PASSWORD}
      - MEILI_HOST=${MEILI_HOST}
      - MEILI_PORT=${MEILI_PORT}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q --server-response http://localhost:8080/v1/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
      redis-backend:
        condition: service_healthy
      meilisearch:
        condition: service_healthy

  crawler:
    image: ghcr.io/${GITHUB_REPOSITORY}/crawler:${IMAGE_TAG:-latest}
    environment:
      - REDIS_CRAWLER_HOST=${REDIS_CRAWLER_HOST}
      - REDIS_PORT=${REDIS_CRAWLER_PORT}
      - REDIS_CRAWLER_PASSWORD=${REDIS_CRAWLER_PASSWORD}
      - MEILI_HOST=${MEILI_HOST}
      - MEILI_PORT=${MEILI_PORT}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      redis-crawler:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY}/frontend:${IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - "127.0.0.1:8084:3000"
    depends_on:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:3000/ > /dev/null || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-backend:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis_data:/data
      - ./db/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "${REDIS_BACKEND_PASSWORD}" ]
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a ${REDIS_BACKEND_PASSWORD} ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-crawler:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis_crawler_data:/data
      - ./db/redis/redis-crawler.conf:/usr/local/etc/redis/redis_crawler.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "${REDIS_CRAWLER_PASSWORD}" ]
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a ${REDIS_CRAWLER_PASSWORD} ping" ]
      interval: 10s
      timeout: 5s
      retries: 5


  meilisearch:
    image: getmeili/meilisearch:v1.7
    restart: unless-stopped
    environment:
      - MEILI_ENV=production
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    volumes:
      - meili_data:/meili_data
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:7700/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  redis_data:
  redis_crawler_data:
  meili_data:
