global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8080']

  - job_name: 'crawler'
    static_configs:
      - targets: ['crawler:8080']

  - job_name: 'indexer'
    static_configs:
      - targets: ['indexer:8080']

  - job_name: 'search-core'
    static_configs:
      - targets: ['search-core:8080']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121'] 

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
