#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_SUPERUSER" --dbname "$POSTGRES_SUPERUSER_DB" <<-EOSQL

CREATE DATABASE ${POSTGRES_BACKEND_DB_NAME};

CREATE USER ${POSTGRES_BACKEND_USER}
WITH PASSWORD '${POSTGRES_BACKEND_PASSWORD}';

GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_BACKEND_DB_NAME} TO ${POSTGRES_BACKEND_USER};

\connect ${POSTGRES_BACKEND_DB_NAME}

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT NOW(),
  last_login TIMESTAMP
);

CREATE TABLE IF NOT EXISTS search_history (
  id SERIAL PRIMARY KEY,
  user_id INT REFERENCES users(id) ON DELETE CASCADE,
  query TEXT NOT NULL,
  searched_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
  id SERIAL PRIMARY KEY,
  user_id INT REFERENCES users(id) ON DELETE CASCADE,
  token TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT NOW(),
  expires_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_search_history_user_id ON search_history(user_id);

ALTER DATABASE ${POSTGRES_BACKEND_DB_NAME} OWNER TO ${POSTGRES_BACKEND_USER};

EOSQL
